// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'auth)': typeof import('./src/components/form/loginButton(with auth).vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/form/input.vue')['default']
    LoginauthButton: typeof import('./src/components/form/loginauthButton.vue')['default']
    LoginButton: typeof import('./src/components/form/loginButton.vue')['default']
    Markdown: typeof import('./src/components/editor/markdown.vue')['default']
    Navmenu: typeof import('./src/components/admin/navmenu.vue')['default']
    Notification: typeof import('./src/components/messagtable/notification.vue')['default']
    Password: typeof import('./src/components/form/password.vue')['default']
    PasswordAuthButton: typeof import('./src/components/form/passwordAuthButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
  }
}
